FROM nginx:latest

ADD ./.docker/nginx/certs/localhost.crt /etc/nginx/ssl/localhost.crt
ADD ./.docker/nginx/certs/localhost.key /etc/nginx/ssl/localhost.key
ADD ./.docker/nginx/nginx.conf /etc/nginx/nginx.conf
